"""Safe, reversible remediation planning and application for TStack."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

from tstack.scanner import ScanReport, scan_project


@dataclass(frozen=True)
class RemediationAction:
    path: str
    description: str
    content: str
    reason: str


@dataclass(frozen=True)
class RemediationResult:
    root: str
    dry_run: bool
    actions: tuple[RemediationAction, ...]
    created: tuple[str, ...]
    skipped: tuple[str, ...]


def _gitignore_content(report: ScanReport) -> str:
    lines = ["# Generated by TStack", ".env", ".env.*", "!.env.example", "*.log", ".DS_Store"]
    frameworks = {item.name for item in report.frameworks}
    if "Python" in frameworks:
        lines += ["__pycache__/", "*.py[cod]", ".pytest_cache/", ".mypy_cache/", ".venv/", "venv/"]
    if "Node.js" in frameworks:
        lines += ["node_modules/", "npm-debug.log*", "yarn-debug.log*", "dist/", ".next/"]
    if "Android/Kotlin" in frameworks:
        lines += [".gradle/", "local.properties", "**/build/", "*.iml"]
    if "Go" in frameworks:
        lines += ["bin/", "coverage.out"]
    if "Rust" in frameworks:
        lines += ["target/"]
    if "PHP" in frameworks:
        lines += ["vendor/"]
    return "\n".join(dict.fromkeys(lines)) + "\n"


def _security_policy() -> str:
    return """# Security Policy

## Reporting a vulnerability

Please report suspected vulnerabilities privately to the project maintainers. Do not disclose exploitable details publicly before a fix is available.

Include affected versions, reproduction steps, impact, and any proposed mitigation. The maintainers will acknowledge the report, assess severity, coordinate remediation, and publish an advisory when appropriate.

## Supported versions

Only the latest maintained release receives security fixes unless the project documents otherwise.
"""


def _ci_content(report: ScanReport) -> str:
    frameworks = {item.name for item in report.frameworks}
    steps = ["      - uses: actions/checkout@v4"]
    if "Python" in frameworks:
        steps += [
            "      - uses: actions/setup-python@v5",
            "        with:",
            "          python-version: '3.12'",
            "      - run: python -m pip install -e '.[dev]'",
            "      - run: pytest",
        ]
    elif "Node.js" in frameworks:
        steps += [
            "      - uses: actions/setup-node@v4",
            "        with:",
            "          node-version: '20'",
            "          cache: npm",
            "      - run: npm ci",
            "      - run: npm test --if-present",
            "      - run: npm run lint --if-present",
        ]
    elif "Go" in frameworks:
        steps += [
            "      - uses: actions/setup-go@v5",
            "        with:",
            "          go-version-file: go.mod",
            "      - run: go test ./...",
        ]
    elif "Rust" in frameworks:
        steps += [
            "      - uses: dtolnay/rust-toolchain@stable",
            "      - run: cargo test --locked",
        ]
    elif "PHP" in frameworks:
        steps += [
            "      - uses: shivammathur/setup-php@v2",
            "        with:",
            "          php-version: '8.3'",
            "      - run: composer install --no-interaction --prefer-dist",
            "      - run: vendor/bin/phpunit",
        ]
    elif "Android/Kotlin" in frameworks:
        steps += [
            "      - uses: actions/setup-java@v4",
            "        with:",
            "          distribution: temurin",
            "          java-version: '17'",
            "      - uses: gradle/actions/setup-gradle@v4",
            "      - run: ./gradlew test lint",
        ]
    else:
        steps += ["      - run: echo 'Add project-specific validation commands'"]
    return "\n".join([
        "name: CI",
        "",
        "on:",
        "  push:",
        "  pull_request:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
        "  validate:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        *steps,
        "",
    ])


def plan_remediation(path: Path) -> tuple[ScanReport, tuple[RemediationAction, ...]]:
    root = path.expanduser().resolve()
    report = scan_project(root)
    actions: list[RemediationAction] = []
    if not report.controls.get("gitignore", False):
        actions.append(RemediationAction(".gitignore", "Create framework-aware ignore rules", _gitignore_content(report), "OPS001"))
    if not report.controls.get("security_policy", False):
        actions.append(RemediationAction("SECURITY.md", "Create responsible-disclosure policy", _security_policy(), "SEC003"))
    if not report.controls.get("ci", False):
        actions.append(RemediationAction(".github/workflows/ci.yml", "Create minimum CI validation workflow", _ci_content(report), "OPS002"))
    return report, tuple(actions)


def apply_remediation(path: Path, *, dry_run: bool = True, force: bool = False) -> RemediationResult:
    root = path.expanduser().resolve()
    if not root.is_dir():
        raise FileNotFoundError(f"project directory not found: {root}")
    _, actions = plan_remediation(root)
    created: list[str] = []
    skipped: list[str] = []
    for action in actions:
        destination = root / action.path
        if destination.exists() and not force:
            skipped.append(action.path)
            continue
        if not dry_run:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(action.content, encoding="utf-8")
            created.append(action.path)
    return RemediationResult(str(root), dry_run, actions, tuple(created), tuple(skipped))


def remediation_json(result: RemediationResult) -> str:
    return json.dumps(asdict(result), indent=2, sort_keys=True) + "\n"


def remediation_markdown(result: RemediationResult) -> str:
    lines = ["# TStack Remediation Plan", "", f"- **Root:** `{result.root}`", f"- **Mode:** {'DRY RUN' if result.dry_run else 'APPLY'}", "", "## Actions", ""]
    if not result.actions:
        lines.append("No safe remediation actions are required.")
    for action in result.actions:
        lines += [f"### `{action.path}`", "", action.description, "", f"- Trigger: `{action.reason}`", ""]
    if result.created:
        lines += ["## Created", "", *[f"- `{item}`" for item in result.created], ""]
    if result.skipped:
        lines += ["## Skipped", "", *[f"- `{item}` already exists" for item in result.skipped], ""]
    lines += ["## Guardrail", "", "TStack only creates missing low-risk control files. It does not modify application code, dependencies, credentials, or existing files unless --force is explicitly supplied.", ""]
    return "\n".join(lines)
